---
title: "slides day 2"
author: "Christopher M. Loan, MS"
date: 'February 21, 2022'
output: xaringan::moon_reader
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ranger)
library(rsample)
library(pdp)
library(vip)
ptitanic <- rpart.plot::ptitanic
```

```{r}
ptitanic <- 
  ptitanic %>% 
  mutate(
    survived = relevel(survived, ref = 'died')
  )

split_data <- initial_split(ptitanic)
training_data <- training(split_data)
testing_data <- testing(split_data)
```

```{r}
# see Malley et al. (2012).

rf_1 <- 
 ranger(
    survived ~ ., 
    data = drop_na(training_data, age),
    importance = 'impurity',
    probability = TRUE
    )
```

```{r}
vip(rf_1)
```

```{r}
partial <- pdp::partial

rf_3_pdp <- 
  partial(
    rf_1, 
    pred.var = c('age', 'sex', 'pclass'),
    type = 'classification',
    which.class = 'survived'
  )
```

```{r}
rf_3_pdp %>% 
  ggplot(
    aes(
      y = yhat, 
      x = age,
      shape = sex
    )
  ) + 
  theme_bw() +
  geom_point(
    size = 4, 
    alpha = 0.4
  ) +
  theme_bw(base_size = 15) +
  theme(
    plot.title.position = 'plot'
    ) +
  facet_wrap(
    vars(pclass), 
    ncol = 1
    )
```

```{r}
testing_data %>% 
  mutate(
    # in this context, the . means "what's carried from the pipe"
    predicted_DT = 
      predict(two_var_DT, newdata = testing_data)[,'survived'], 
    predicted_glm = 
      predict(
        glm_comparison,
        newdata = testing_data, 
        type = 'response'
        ), 
    predicted_rf = 
       predict(rf_1, data = testing_data),#[,'survived']
    actual = survived
  )
```

